### ISSUE TITLE
Quicktest doesn't display the bad input in some cases

### ISSUE THREAD

**Issue by mratsim** [alehander42/nim-quickcheck#3]
I think it maybe because they are on the same side of the `==` sign

```Nim
suite "Foo":
  let hi = 1'u shl (sizeof(uint)*7)
  quicktest "`or`", 10_000 do(x: uint(min=0, max=hi), y: uint(min=0, max=hi)):
    check(0'u == (x or y))
```

_This works though:_
```Nim
    let z = (x or y)
    check(0'u == z)
```

Actually no, it displays the z value not the x and y value.
    `check(x == y)`
would display something however

**Comment by alehander92** [comment]
Now you should always see your generated variables on error
